language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - libuhd-dev
      - libfftw3-dev

compiler:
  - gcc
  - clang

script:
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure --disable-zeromq
    make
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure
    make
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure --enable-kiss-fft --enable-fft-simd
    make

