language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - libfftw3-dev
      # libuhd-dev is not allowed
      - g++-6

compiler:
  - gcc

script:
  - |
    ./bootstrap.sh
    CC=gcc-6 CXX=g++-6 ./configure --disable-zeromq --disable-output-uhd
    make
  - |
    ./bootstrap.sh
    CC=gcc-6 CXX=g++-6 ./configure --disable-output-uhd
    make
  - |
    ./bootstrap.sh
    CC=gcc-6 CXX=g++-6 ./configure --disable-output-uhd --disable-native
    make

